#!/usr/bin/env python3
"""Generate config options documentation from constants.

Usage:
    uv run python tools/generate_config_docs.py > docs/config_options.md
"""
from __future__ import annotations

import argparse
import json

from lawqa_rag_studio.config.constants import ALL_CONFIG_ENUMS, ConfigOption


def generate_markdown_table() -> str:
    """Generate documentation in Markdown table format.

    Returns:
        Markdown string.
    """
    lines = [
        "# Config Options",
        "",
        "> This document is auto-generated by tools/generate_config_docs.py.",
        "> Do not edit manually.",
        "",
        "| Path | Option | Description | Default |",
        "|------|--------|-------------|---------|",
    ]
    for config_path, enum_cls in ALL_CONFIG_ENUMS.items():
        for member in enum_cls:
            opt: ConfigOption = member.value
            default_mark = "✓" if opt.default else ""
            lines.append(
                f"| `{config_path}` | `{opt.value}` | {opt.description} | {default_mark} |"
            )
    return "\n".join(lines)


def generate_json() -> str:
    """Generate documentation in JSON format.

    Returns:
        JSON string.
    """
    result = {}
    for config_path, enum_cls in ALL_CONFIG_ENUMS.items():
        result[config_path] = {
            "options": [
                {
                    "value": member.value.value,
                    "description": member.value.description,
                    "default": member.value.default,
                }
                for member in enum_cls
            ]
        }
    return json.dumps(result, ensure_ascii=False, indent=2)


def main() -> None:
    """CLI entrypoint for documentation generation."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--format", choices=["table", "json"], default="table")
    args = parser.parse_args()
    if args.format == "table":
        print(generate_markdown_table())
    else:
        print(generate_json())


if __name__ == "__main__":
    main()
